name: CI/CDl.

on:
  push:
    branches:
      - winnie
      - develop 
      
  pull_request:
    branches:
      -winnie

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: 18.x

    - name: Installer les dépendances Node.js
      run: npm install

    - name: Run tests with code coverage
      uses: coactions/setup-xvfb@v1
      with:
        run: npm run test -- --no-watch --code-coverage
      